name: niddler_dart
description: Niddler network inspector for dart and flutter! Use the niddler IntelliJ and Android Studio plugin to debug your network requests during development.
version: 0.11.0-nullsafety.0
homepage: https://github.com/Chimerapps/niddler_dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  dart_service_announcement: ^1.0.0-nullsafety.1
  stack_trace: ^1.10.0-nullsafety.6
  synchronized: ^3.0.0-nullsafety.1

dev_dependencies:
  http: ^0.12.0+1
  pedantic: ^1.10.0-nullsafety.3
