name: niddler_dart
description: Niddler network inspector for dart and flutter! Use the niddler IntelliJ and Android Studio plugin to debug your network requests during development.
version: 1.3.0
homepage: https://github.com/Chimerapps/niddler_dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dart_service_announcement: ^1.0.0
  stack_trace: ^1.10.0
  synchronized: ^3.0.0
  worker_manager: ^4.2.6

dev_dependencies:
  http: ^0.13.3
  lints: ^1.0.1
