name: niddler_dart
description: Niddler network inspector for dart and flutter! Use the niddler IntelliJ and Android Studio plugin to debug your network requests during development.
version: 0.10.4
homepage: https://github.com/Chimerapps/niddler_dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  synchronized: ^2.1.0
  uuid: ^2.0.1
  stack_trace: ^1.9.3
  meta: ^1.1.8
  dart_service_announcement: ^0.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0
  http: ^0.12.0+1
