name: niddler_dart
description: Niddler network inspector for dart and flutter! Use the niddler IntelliJ and Android Studio plugin to debug your network requests during development.
version: 1.4.1
homepage: https://github.com/Chimerapps/niddler_dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  computer: ^3.2.1
  dart_service_announcement: ^1.0.0
  stack_trace: ^1.10.0
  synchronized: ^3.0.0

dev_dependencies:
  http: ^0.13.3
  lints: ^1.0.1
